name: Daily Automation

on:
  schedule:
    - cron: '29 23 * * *'  # Rodar diariamente às 23:29 UTC
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar Dependências
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Rodar o Script
        run: python script.py
        env:
          DISPLAY: :99  # Necessário para rodar o Chromium em um ambiente sem cabeça (headless)
