name: Python Automation Workflow

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  run_script:
    runs-on: ubuntu-latest  # Definindo o sistema operacional para o runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    
    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y wget

    - name: Set up Chrome options for Selenium
      run: |
        echo "export CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
        echo "export DISPLAY=:99" >> $GITHUB_ENV
    
    - name: Run Python script
      run: |
        python script.py
