name: Run Script at Midnight

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  run:
    runs-on: ubuntu-latest  # Ambiente de execução no GitHub Actions (Ubuntu)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz o checkout do repositório

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Defina a versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências

      - name: Run the Python script
        run: |
          python script.py  # Execute seu script Python
