name: Rodar script Selenium

on:
  schedule:
    - cron: '10 3 * * *'  # Hora de Brasília (UTC-3) = 03h10 UTC

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python e dependências
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          wget -q -O chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")/chromedriver_linux64.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Rodar o script Selenium
        run: |
          python script.py | tee output.log

      - name: Upload de logs para depuração
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-logs
          path: output.log
