name: Rodar script Selenium

on:
  schedule:
    - cron: '0 3 * * *'  # Hora de Brasília (UTC-3) = 03h00 UTC

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python e dependências
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium chromedriver-autoinstaller

      - name: Rodar o script Selenium
        run: |
          python script.py  # Certifique-se de que este é o nome correto do script
