name: Agendar Reserva

on:
  schedule:
    - cron: '10 3 * * *'  # Hora de Brasília (UTC-3) = 03h10 UTC
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub Actions

jobs:
  reserva:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y unzip
          wget -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.94/linux64/chromedriver-linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          wget -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/google-chrome.deb || sudo apt --fix-broken install -y

      - name: Configurar ambiente Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Instalar bibliotecas Python
        run: pip install selenium

      - name: Executar script de reserva
        env:
          EMAIL: ${{ secrets.DESKBEE_EMAIL }}
          SENHA: ${{ secrets.DESKBEE_SENHA }}
        run: python reserva.py
