name: Agendar Reserva

on:
  schedule:
    - 
#cron: '0 3 * * *'  # Hora de Brasília (UTC-3) = 03h10 UTC
  workflow_dispatch:

jobs:
  reserva:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Verificar instalação do Chrome
        run: google-chrome --version

      - name: Configurar ambiente Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Instalar bibliotecas Python
        run: pip install selenium webdriver-manager

      - name: Executar script de reserva
        env:
          EMAIL: ${{ secrets.DESKBEE_EMAIL }}
          SENHA: ${{ secrets.DESKBEE_SENHA }}
        run: python reserva.py

      - name: Registrar saída do Selenium (se falhar)
        if: failure()
        run: cat /tmp/chromedriver.log || true
